id: I9A5EB07F
legacy_id: P009450
ocr_import_info:
  bdrc_scan_id: W1KG4477
  source: bdrc
  ocr_info:
    timestamp: '2020-03-27T09:59:07'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T16:43:03.028010+00:00'
last_modified: 2022-09-01 00:43:34.238174
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG4477
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG4477
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: སྟོན་པའི་སྐྱེས་རབས།
  author: སློབ་དཔོན་དཔའ་བོ།
statistics:
  ocr_word_mean_confidence_index: 0.7231849273181954
  ocr_word_median_confidence_index: 0.7599999904632568
quality: null
bases:
  I1KG4510:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG4510
      total_pages: 626
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG4510.txt
    statistics:
      ocr_word_median_confidence_index: 0.7799999713897705
      ocr_word_mean_confidence_index: 0.7348110921382786
    legacy_id: v001
  I1KG4511:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG4511
      total_pages: 638
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1KG4511.txt
    statistics:
      ocr_word_median_confidence_index: 0.7400000095367432
      ocr_word_mean_confidence_index: 0.7097014546361101
    legacy_id: v002
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
