id: P009450
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-19 19:39:22.683777
source_metadata:
  id: bdr:W1KG4477
  title: སྟོན་པའི་སྐྱེས་རབས
  author: ''
  volumes:
    3d468bde82034219bd89104688890a53:
      image_group_id: I1KG4510
      title: ''
      volume_number: 1
      total_pages: 626
      base_file: v001.txt
    6d0e46aa4edb420092db8416ec786a9d:
      image_group_id: I1KG4511
      title: ''
      volume_number: 2
      total_pages: 638
      base_file: v002.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
